name: shuwaikh
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  # for adapting screen and font size.  
  flutter_screenutil: ^5.9.0
  # An SVG rendering and widget library for Flutter
  flutter_svg: ^2.0.10+1
  # localization
  intl: ^0.18.1
  easy_localization: ^3.0.3
  # Networking
  dio: ^5.3.3
  retrofit: ^4.0.3
  retrofit_generator: ^8.0.4
  pretty_dio_logger: ^1.3.1
  # Automatically generate code for converting to and from JSON by annotating Dart classes
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1 
   #A build system for Dart code generation and modular compilation
  build_runner: ^2.4.7
  # State management
  flutter_bloc: ^8.1.3
  # Code generator (mainly used with cubit & retrofit)
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  # for dependency injection
  get_it: ^7.6.4
  # firebase service
  firebase_core: ^2.30.0
  firebase_auth: ^4.19.2
  # auth
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^6.2.0
  # generate pin code fields
  pin_code_fields: ^8.0.1
dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
  #   - assets/images/banner/
  #   - assets/images/product/
    # - assets/images/
 
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand/Quicksand-Bold.ttf
        - asset: assets/fonts/Quicksand/Quicksand-SemiBold.ttf
        - asset: assets/fonts/Quicksand/Quicksand-Medium.ttf
        - asset: assets/fonts/Quicksand/Quicksand-Light.ttf

