name: shuwaikh
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  bloc: ^8.1.4
  build_runner: ^2.4.9
  cached_network_image: ^3.3.1
  carousel_slider_plus: ^7.0.0
  clipboard: ^0.1.3
  cupertino_icons: ^1.0.6
  curved_navigation_bar: ^1.0.3
  dartz: ^0.10.1
  dio: ^5.3.3
  firebase_auth: ^4.19.2
  firebase_core: ^2.30.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_facebook_auth: ^6.2.0
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.10+1
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  get_it: ^7.7.0
  google_sign_in: ^6.2.1
  image_picker: ^1.1.1
  intl: ^0.19.0
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  pin_code_fields: ^8.0.1
  pretty_dio_logger: ^1.3.1
  readmore: ^3.0.0
  retrofit: ^4.0.3
  retrofit_generator: ^8.0.4
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0
  webview_flutter: ^4.9.0
dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    #   - assets/images/banner/
    #   - assets/images/product/
    - assets/images/

  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/quicksand/Quicksand-Bold.ttf
        - asset: assets/fonts/quicksand/Quicksand-SemiBold.ttf
        - asset: assets/fonts/quicksand/Quicksand-Medium.ttf
        - asset: assets/fonts/quicksand/Quicksand-Regular.ttf
        - asset: assets/fonts/quicksand/Quicksand-Light.ttf

flutter_intl:
  enabled: true
